# Generated by Django 2.1.7 on 2019-05-08 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kifu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('position', models.IntegerField()),
                ('board_black', models.BigIntegerField(default=68853694464)),
                ('board_white', models.BigIntegerField(default=34628173824)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Taikyoku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_black_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_black', to='VS_othello.Player')),
                ('player_white_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_white', to='VS_othello.Player')),
            ],
        ),
        migrations.AddField(
            model_name='kifu',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VS_othello.Player'),
        ),
        migrations.AddField(
            model_name='kifu',
            name='taikyoku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VS_othello.Taikyoku'),
        ),
    ]
